"""
上下文管理模块 — 为 Nexent Agent 提供基于 LLM 摘要的上下文压缩能力。
 
设计原则：
  1. 独立模块，不修改现有类的继承关系
  2. 通过开关控制，关闭时行为与原系统完全一致（baseline）
  3. 基于 token 阈值触发压缩，而非固定轮次截断
  4. 使用 LLM 生成结构化摘要替换旧步骤，保留语义而非丢弃信息
  5. 保留最近 N 步不压缩，保证当前推理链完整
 
 
用法：
  在 nexent_agent.py 中：
    from .context_manager import ContextManager, ContextManagerConfig
 
    # 创建（关闭状态 = baseline）
    ctx_mgr = ContextManager(config=ContextManagerConfig(enabled=False))
 
    # 创建（开启状态）
    ctx_mgr = ContextManager(config=ContextManagerConfig(
        enabled=True,
        token_threshold=60000,
        keep_recent_steps=6,
    ))
 
    # 在 agent 推理前调用
    ctx_mgr.compress_if_needed(agent.memory, model)
 
    # 对跨 run 历史调用
    history = ctx_mgr.trim_history(history)
"""



import json 
import logging
from dataclasses import dataclass, field 
from typing import Any, Dict, List, Optional, TYPE_CHECKING
from smolagents.memory import ActionStep, TaskStep, AgentMemory, MemoryStep
from smolagents.models import ChatMessage, MessageRole

logger = logging.getLogger("agent_context")

@dataclass 
class AgentContextManagerConfig:
    """
    Context manager configuration with sensible defaults for all fields.
    """

    enabled: bool = False
    """Master switch. False = baseline mode, no compression."""

    token_threshold: int = 60000
    """Token estimation threshold that triggers compression. Triggers compression
    when the estimated token count of all serialized steps in memory exceeds this value.
    Recommended to set 60%-75% of the model's context window."""

    keep_recent_steps: int = 4
    """Number of most recent steps to keep untouched during compression.
    These steps contain critical context for the current reasoning chain and should not be compressed.
    Note: this value must be less than AgentConfig.max_steps, otherwise in-run compression will never trigger.
    Composition of memory.steps = [cross-run injected historical steps] + [TaskStep + ActionStep sequences] of 
    the current run.
        - Each cross-run conversation round occupies 2 steps (TaskStep + ActionStep[Final Answer retains])
        - Each execution step of current run occupies 1 ActionStep, and each run may have MANY ActionStep TO COMPLETE
    Recommended to set max(2, max_steps//2) to ensure at least some steps can be compressed.
    """

    max_history_rounds: int = 20
    """Maximum number of conversation rounds to retain across runs (1 round = 1 user + 1 assistant).
    Excess will be compressed via LLM summarization (rather than directly discarded)"""

    max_history_content_length: int = 3000
    """Maximum characters for a single message in cross-run history. Exceeding content will be truncted and marked"""

    max_observation_length: int = 500
    """Maximum characters to retain for old step observations."""


    summary_system_prompt: str = (
        "你是一个对话摘要助手。请将以下对话历史压缩为结构化摘要，"
        "保留所有关键信息：用户的核心需求、已完成的工作、重要发现和决策、"
        "待办事项、需要保留的上下文。输出严格 JSON 格式，不要包含 markdown 代码块标记。"
    )

    summary_json_schema: Dict[str, Any] = field(default_factory=lambda: {
        "task_overview": "用户的核心请求与成功标准（≤150字）",
        "completed_work": "已完成的工作、产出的文件或结果（≤200字）",
        "key_decisions": "重要发现、做出的决策及其理由（≤200字）",
        "pending_items": "待完成的具体步骤、阻塞项（≤150字）",
        "context_to_preserve": "用户偏好、领域细节、做出的承诺（≤150字）",
    })
    """摘要的 JSON schema 描述，作为 prompt 的一部分引导 LLM 输出。"""


    max_summary_input_chars: int = 30000
    """Maximum input characters to send to the summarization LLM.
    When exceeded, older content will be further truncated to prevent 
    the summary call itself from exceeding the model context."""


    chars_per_token: float = 1.5
    """Rough character/token conversion ratio for token estimation.
    Chinese: approximately 0.8-1.5 chars/token, English: approximately 3.5-4.5 chars/token.
    Default 2.5 leans toward Chinese scenarios (Nexent's primary language),
    Slightly overestimating token count to trigger compression early is preferable to underestimating and causing OOM.
    For pure English scenarios, recommend adjusting to 4.0."""



@dataclass
class SummaryTaskStep(TaskStep):
    """Special TaskStep, summary generated by LLM 
    
    Inherits from TaskStep (dataclass) to maintain serialization compatibility (e.g., dict()),
    while overriding to_messages() to prevent the base class's default "New Task:" prefix from misleading
    the model into treating the summary as a new task.
    """
    is_summary: bool = True
 
    def to_messages(self, summary_mode: bool = False) -> list:
        content = [{"type": "text", "text": f"Previous context summary:\n{self.task}"}]
        return [ChatMessage(role=MessageRole.USER, content=content)]

class ContextManager:
    """Non-intrusive standalone context manager.

    Usage:
    1. compress_if_needed() at CoreAgent._step_stream start (before 
        write_memory_to_messages)
    2. trim_history() in NexentAgent.add_history_to_agent for cross-run history
    """
 
    def __init__(self, config: Optional[AgentContextManagerConfig] = None, max_steps: Optional[int] = None):
        self.config = config or AgentContextManagerConfig()
        self._compression_count = 0
        
        # Validate and adjust keep_recent_steps based on max_steps
        if max_steps is not None and self.config.keep_recent_steps >= max_steps:
            # Ensure at least one step can be compressed
            self.config.keep_recent_steps = max(1, max_steps - 1)
            logger.warning(
                f"keep_recent_steps ({config.keep_recent_steps if config else 'default'}) "
                f"is >= max_steps ({max_steps}), adjusted to {self.config.keep_recent_steps}"
            )

            
    def compress_if_needed(
            self,
            memory: AgentMemory,
            model: Any,
        ) -> bool:
            """检查 memory 中的 token 量，超过阈值则压缩旧步骤。
    
            Args:
                memory: smolagents AgentMemory 实例
                model: 可调用的 LLM 模型（用于生成摘要）
    
            Returns:
                是否执行了压缩
            """
            if not self.config.enabled:
                return False
    
            estimated_tokens = self._estimate_tokens(memory)
            if estimated_tokens <= self.config.token_threshold:
                return False
    
            logger.info(
                f"上下文压缩触发: 估算 {estimated_tokens} tokens > 阈值 {self.config.token_threshold}"
            )
            self._do_compress(memory, model)
            return True
        
    def trim_history(
            self,
            history: List[Any],
            model: Any = None,
        ) -> List[Any]:
            """处理跨 run 的对话历史。
    
            策略：
            - 如果 enabled=False，原样返回（baseline）
            - 如果历史轮次在阈值内，仅做单条内容长度截断
            - 如果超出 max_history_rounds，用 LLM 摘要压缩早期历史
                （如果 model 不可用，则退化为保留最近 N 轮）
    
            注意：切分点始终对齐到完整的 user→assistant 对话轮次边界，
            避免出现孤立的 user 或 assistant 消息。
    
            Args:
                history: AgentHistory 列表
                model: 可选的 LLM 模型，用于摘要（无则退化为截断）
    
            Returns:
                处理后的历史列表
            """
            if not self.config.enabled or not history:
                return history
    
            max_items = self.config.max_history_rounds * 2
    
            if len(history) <= max_items:
                return self._truncate_long_messages(history)
    
            # 找到对齐到轮次边界的切分点
            split_idx = self._find_pair_boundary(history, max_items)
            old_history = history[:split_idx]
            recent_history = history[split_idx:]
    
            if model is not None and old_history:
                summary_text = self._summarize_history_with_llm(old_history, model)
                if summary_text:
                    from .agent_model import AgentHistory
                    # 摘要用 assistant 角色注入，原因：
                    # 1. 语义上：摘要是"系统对之前对话的总结"，更接近 assistant
                    # 2. 结构上：recent_history 以 user 开头（_find_pair_boundary 保证），
                    #    如果摘要也是 user，会产生连续双 user 消息，
                    #    部分 LLM API（尤其国产模型）对此会报错
                    # 3. add_history_to_agent 中 assistant → ActionStep，
                    #    后接 TaskStep(user) → ActionStep(assistant)，严格交替
                    summary_msg = AgentHistory(
                        role="assistant",
                        content=f"[以下是之前对话的上下文摘要]\n{summary_text}"
                    )
                    return [summary_msg] + self._truncate_long_messages(recent_history)
    
            logger.warning("无可用模型或摘要失败，退化为截断跨 run 历史")
            return self._truncate_long_messages(recent_history)
    
        # 截断标记常量，用于幂等性检测
    _OBSERVATION_TRUNCATION_MARKER = "\n... [observations truncated for context efficiency]"


    def compress_old_observations(self, memory: AgentMemory) -> None:
        """轻量级优化：截短旧步骤的 observations 字段。
 
        这是一个不需要 LLM 的廉价操作，可以在每步结束后调用。
        跳过最后一个步骤（刚刚 append 的当前步骤），只处理更早的历史步骤。
        幂等：已截断过的 observations 不会被重复处理。
 
        Args:
            memory: AgentMemory 实例
        """
        if not self.config.enabled:
            return
 
        max_chars = self.config.max_observation_length
 
        # 跳过最后一个步骤：它是刚 append 的当前步骤，
        # 其 observations 可能在后续流程中还会被读取
        steps_to_process = memory.steps[:-1] if len(memory.steps) > 1 else []
 
        for step in steps_to_process:
            if isinstance(step, ActionStep) and step.observations:
                # 幂等性保护：已经截断过的不再处理
                if step.observations.endswith(self._OBSERVATION_TRUNCATION_MARKER):
                    continue
                if len(step.observations) > max_chars:
                    step.observations = (
                        step.observations[:max_chars]
                        + self._OBSERVATION_TRUNCATION_MARKER
                    )

    @staticmethod
    def _find_pair_boundary(history: List[Any], keep_count: int) -> int:
        """从列表末尾向前找到一个对齐到 user 消息开头的切分点。
 
        确保 recent 部分以 user 消息开头（完整的对话轮次），
        old 部分以 assistant 消息结尾（不会有孤立的 user）。
 
        Args:
            history: AgentHistory 列表
            keep_count: 期望保留的近期消息数量
 
        Returns:
            切分索引，history[:idx] 为旧消息，history[idx:] 为保留消息
        """
        raw_split = max(0, len(history) - keep_count)
 
        # 从 raw_split 位置向后扫描，找到第一个 role='user' 的位置
        for i in range(raw_split, len(history)):
            if hasattr(history[i], 'role') and history[i].role == 'user':
                return i
 
        # 如果后半段全是 assistant（极端情况），保持原切分
        return raw_split

    def _find_safe_step_split(self, steps: List[MemoryStep], keep_recent: int) -> int:
        """在 memory.steps 中找到安全的切分点。
 
        smolagents 的 memory.steps 结构为：
          [TaskStep, ActionStep, ActionStep, ..., TaskStep, ActionStep, ...]
 
        策略：
          - 如果 recent 范围内有 TaskStep，对齐到最近的 TaskStep 边界
          - 如果整个 steps 只有一个 TaskStep（典型的单 run 场景），
            允许在 ActionStep 之间切分（它们是自包含的原子单元，
            且 TaskStep 的内容会被摘要保留）
 
        Args:
            steps: memory.steps 列表
            keep_recent: 期望保留的最近步骤数
 
        Returns:
            切分索引。返回 0 表示没有可压缩的内容。
        """
        if len(steps) <= keep_recent:
            return 0
 
        raw_split = len(steps) - keep_recent
 
        # 统计 raw_split 之后有多少个 TaskStep
        task_steps_in_recent = [
            i for i in range(raw_split, len(steps))
            if isinstance(steps[i], TaskStep)
        ]
 
        if task_steps_in_recent:
            # recent 范围内有 TaskStep → 对齐到第一个 TaskStep
            return task_steps_in_recent[0]
 
        # recent 范围内没有 TaskStep
        # 检查是否是"单 TaskStep"场景（整个 steps 只有开头一个 TaskStep）
        task_step_count = sum(1 for s in steps if isinstance(s, TaskStep))
 
        if task_step_count <= 1:
            # 单 TaskStep 场景：整个 run 只有一个 task
            # TaskStep 在 index 0，后面全是 ActionStep
            # 直接在 raw_split 切分是安全的：
            #   - ActionStep 是自包含的（有 model_output + observations）
            #   - TaskStep 的内容（用户原始 query）会被摘要保留
            #   - 如果已有 SummaryTaskStep，也会被包含在旧步骤中重新摘要
            return raw_split
 
        # 多 TaskStep 场景：向前找最近的 TaskStep，将其连同后续 ActionStep 保留
        for i in range(raw_split - 1, -1, -1):
            if isinstance(steps[i], TaskStep):
                return i
 
        return raw_split

 
    def _estimate_tokens(self, memory: AgentMemory) -> int:
        """估算 memory 中当前上下文的 token 数。
 
        优先使用最后一个 ActionStep 的 input_tokens（它代表该步调用时的
        完整上下文长度），再加上该步之后新增步骤的文本估算。
 
        注意：不能简单累加所有步骤的 input_tokens，因为每步的 input_tokens
        已经是累积值（包含了前面所有步骤的内容）。
        """
        # 策略1：找最后一个有 token_usage 的 ActionStep
        last_known_tokens = 0
        last_known_idx = -1
        for i, step in enumerate(memory.steps):
            if isinstance(step, ActionStep) and step.token_usage:
                last_known_tokens = step.token_usage.input_tokens
                last_known_idx = i
 
        if last_known_tokens > 0:
            # 加上 last_known_idx 之后新增步骤的估算增量
            incremental_chars = 0
            for step in memory.steps[last_known_idx + 1:]:
                for msg in step.to_messages():
                    incremental_chars += self._msg_char_count(msg)
            return last_known_tokens + int(incremental_chars / self.config.chars_per_token)
 
        # 策略2：完全基于字符数估算
        total_chars = 0
        if memory.system_prompt:
            for msg in memory.system_prompt.to_messages():
                total_chars += self._msg_char_count(msg)
        for step in memory.steps:
            for msg in step.to_messages():
                total_chars += self._msg_char_count(msg)
        return int(total_chars / self.config.chars_per_token)
 
    @staticmethod
    def _msg_char_count(msg: ChatMessage) -> int:
        """计算单条 ChatMessage 的字符数。"""
        if isinstance(msg.content, str):
            return len(msg.content)
        if isinstance(msg.content, list):
            count = 0
            for block in msg.content:
                if isinstance(block, dict) and block.get("type") == "text":
                    count += len(block.get("text", ""))
            return count
        return 0


    def _do_compress(self, memory: AgentMemory, model: Any) -> None:
        """执行压缩：用 LLM 摘要替换旧步骤。
 
        切分时保证步骤组的完整性（参见 _find_safe_step_split）。
        """
        steps = memory.steps
        keep_n = self.config.keep_recent_steps
 
        if len(steps) <= keep_n:
            return
 
        split_idx = self._find_safe_step_split(steps, keep_n)
        if split_idx == 0:
            return
 
        old_steps = steps[:split_idx]
        recent_steps = steps[split_idx:]
 
        old_text = self._steps_to_text(old_steps)
 
        summary_text = self._generate_summary(old_text, model)
 
        if summary_text:
            summary_step = SummaryTaskStep(
                task=f"[对话上下文摘要 - 第{self._compression_count + 1}次压缩]\n{summary_text}",
            )
            memory.steps = [summary_step] + recent_steps
            self._compression_count += 1
            logger.info(
                f"压缩完成：{len(old_steps)} 个旧步骤 → 1 个摘要步骤，"
                f"保留 {len(recent_steps)} 个近期步骤"
            )
        else:
            logger.warning("摘要生成失败，跳过本次压缩")
                
    def _steps_to_text(self, steps: List[MemoryStep]) -> str:
            """将步骤列表序列化为可读文本，用于 LLM 摘要输入。
    
            对总长度做上限控制，避免摘要调用本身超出模型上下文。
            """
            max_total = self.config.max_summary_input_chars
            parts = []
            total_chars = 0
    
            for step in steps:
                for msg in step.to_messages():
                    role = getattr(msg, 'role', 'unknown')
                    role_str = role.value if hasattr(role, 'value') else str(role)
    
                    if isinstance(msg.content, str):
                        text = msg.content
                    elif isinstance(msg.content, list):
                        text = " ".join(
                            block.get("text", "")
                            for block in msg.content
                            if isinstance(block, dict) and block.get("type") == "text"
                        )
                    else:
                        text = str(msg.content)
    
                    if not text.strip():
                        continue
    
                    # 单条消息截断
                    if len(text) > 2000:
                        text = text[:2000] + "... [truncated]"
    
                    entry = f"[{role_str}]: {text}"
    
                    # 总长度控制
                    if total_chars + len(entry) > max_total:
                        remaining = max_total - total_chars
                        if remaining > 100:
                            parts.append(entry[:remaining] + "... [input limit reached]")
                        break
    
                    parts.append(entry)
                    total_chars += len(entry)
    
            return "\n\n".join(parts)

    def _generate_summary(self, text: str, model: Any) -> Optional[str]:
            """调用 LLM 生成结构化摘要。
    
            使用 system + user 消息的标准格式调用模型。
            """
            schema_desc = json.dumps(
                self.config.summary_json_schema, ensure_ascii=False, indent=2
            )
            user_prompt = (
                f"请按以下 JSON 结构输出摘要：\n{schema_desc}\n\n"
                f"需要摘要的对话内容：\n{text}"
            )
    
            try:
                from smolagents.models import ChatMessage, MessageRole
                messages = [
                    ChatMessage(
                        role=MessageRole.SYSTEM,
                        content=[{"type": "text", "text": self.config.summary_system_prompt}]
                    ),
                    ChatMessage(
                        role=MessageRole.USER,
                        content=[{"type": "text", "text": user_prompt}]
                    ),
                ]
                response = model(messages, stop_sequences=[])
    
                # [修复] 处理返回值：ChatMessage.content 可能是 str 或 list[dict]
                raw_output = response.content
                if isinstance(raw_output, list):
                    raw_output = " ".join(
                        block.get("text", "")
                        for block in raw_output
                        if isinstance(block, dict) and block.get("type") == "text"
                    )
                if not isinstance(raw_output, str):
                    raw_output = str(raw_output)
    
                return self._format_summary(raw_output)
    
            except Exception as e:
                logger.error(f"摘要生成异常: {e}")
                return None


    @staticmethod
    def _format_summary(raw: str) -> Optional[str]:
        """将 LLM 的原始输出格式化为结构化摘要文本。
 
        Returns:
            格式化后的摘要文本，或内容为空时返回 None
        """
        if not raw or not raw.strip():
            return None
 
        # 尝试提取 JSON（处理 markdown 代码块包裹）
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            first_newline = cleaned.find("\n")
            if first_newline != -1:
                cleaned = cleaned[first_newline + 1:]
            if cleaned.rstrip().endswith("```"):
                cleaned = cleaned.rstrip()[:-3]
            cleaned = cleaned.strip()
 
        try:
            data = json.loads(cleaned)
            label_map = {
                "task_overview": "任务概述",
                "completed_work": "已完成工作",
                "key_decisions": "关键决策",
                "pending_items": "待办事项",
                "context_to_preserve": "需保留上下文",
            }
            parts = []
            for key, label in label_map.items():
                value = data.get(key, "")
                if value:
                    parts.append(f"## {label}\n{value}")
            if parts:
                return "\n\n".join(parts)
        except (json.JSONDecodeError, AttributeError, TypeError):
            pass
 
        # JSON 解析失败，直接使用原始文本
        return cleaned if cleaned else None
 
    def _summarize_history_with_llm(
        self, history: List[Any], model: Any
    ) -> Optional[str]:
        """将跨 run 的旧历史轮次用 LLM 压缩为摘要。
 
        对总输入长度做上限控制。
        """
        max_total = self.config.max_summary_input_chars
        parts = []
        total_chars = 0
 
        for msg in history:
            content = msg.content
            if len(content) > 1500:
                content = content[:1500] + "..."
            entry = f"[{msg.role}]: {content}"
 
            if total_chars + len(entry) > max_total:
                break
 
            parts.append(entry)
            total_chars += len(entry)
 
        if not parts:
            return None
 
        text = "\n\n".join(parts)
        return self._generate_summary(text, model)
 
    def _truncate_long_messages(self, history: List[Any]) -> List[Any]:
        """截断历史中过长的单条消息。返回新列表，不修改原对象。"""
        max_len = self.config.max_history_content_length
        result = []
        for msg in history:
            if len(msg.content) > max_len:
                from .agent_model import AgentHistory
                result.append(AgentHistory(
                    role=msg.role,
                    content=msg.content[:max_len] + "\n... [content truncated]"
                ))
            else:
                result.append(msg)
        return result